version: '3.8'

services:
  db:
    container_name: franken_mariadb
    image: mariadb:10.11.9
    restart: always
    user: ${UID}:${GID}
    volumes:
      - ${PWD}/database:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
      - '[::1]:3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: TS2DHFaAfENQ
    networks:
      - franken_network

  phpmyadmin:
    container_name: franken_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: franken_mariadb
      PMA_USER: root
      PMA_PASSWORD: TS2DHFaAfENQ
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - franken_network

  cache:
    container_name: franken_redis
    image: redis:alpine
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - franken_network

  franken-php:
    container_name: webserver-and-caddy
    image: custom-frankenphp:latest
    restart: always
    network_mode: host
    user: ${UID}:${GID}
    volumes:
      - ${CUSTOM_PATH}:/${CUSTOM_PATH}
      - ${PWD}/caddy/data:/data
      - ${PWD}/caddy/config:/config
      - ${PWD}/caddy/certs:/certs
      - ${PWD}/caddy/log:/var/log
      - ${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/caddy/sites:/etc/caddy/sites
      - ${PWD}/php/php.ini:/usr/local/etc/php/php.ini

networks:
  franken_network:
    driver: bridge