services:
  db:
    container_name: franken_mariadb
    image: mariadb:10.11.9
    restart: always
    user: ${UID}:${GID}
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - ${DB_PORT:-127.0.0.1:3306:3306}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - franken_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    container_name: franken_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: franken_mariadb
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - ${PMA_PORT:-127.0.0.1:8080:80}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - franken_network

  cache:
    container_name: franken_redis
    image: redis:alpine
    restart: always
    command: redis-server
    ports:
      - ${REDIS_PORT:-127.0.0.1:6379:6379}
    networks:
      - franken_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  franken-php:
    container_name: webserver-and-caddy
    image: custom-frankenphp:latest
    restart: always
    network_mode: host
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - ${CUSTOM_PATH}:/${CUSTOM_PATH}
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/certs:/certs
      - ./caddy/log:/var/log
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/sites:/etc/caddy/sites
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

networks:
  franken_network:
    driver: bridge
