services:
  db:
    container_name: mariadb
    image: mariadb:10.11.9
    restart: unless-stopped
    network_mode: host
    user: ${UID}:${GID}
    volumes:
      - ${PWD}/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: REDACTED_PASSWORD

  franken-php:
    container_name: webserver-and-caddy
    image: custom-frankenphp:latest
    restart: unless-stopped
    network_mode: host
    user: ${UID}:${GID}
    volumes:
      - ${CUSTOM_PATH}:/${CUSTOM_PATH}
      - /media:/media
      - ${PWD}/caddy/data:/data
      - ${PWD}/caddy/config:/config
      - ${PWD}/caddy/certs:/certs
      - /etc/letsencrypt:/etc/letsencrypt
      - ${PWD}/caddy/log:/var/log
      - ${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/caddy/sites:/etc/caddy/sites
      - ${PWD}/php/php.ini:/usr/local/etc/php/php.ini